# Generated by Django 5.2.6 on 2025-09-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Car_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Car_name', models.CharField(max_length=100)),
                ('Release_date', models.DateField()),
                ('Brand', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
